# Generated by Django 4.2.14 on 2024-07-13 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EquipmentType',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('serial_number_mask', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('code', models.AutoField(primary_key=True, serialize=False)),
                ('serial_number', models.CharField(max_length=20, unique=True)),
                ('note', models.TextField()),
                ('equipment_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='apiTechnicalSpecification.equipmenttype')),
            ],
        ),
    ]
